### ISSUE TITLE
Support docker functionality in Gitea CI tasks

### ISSUE THREAD

**Issue by dboreham** [cerc-io/hosting#24]
Gitea's act runner as-is didn't support full docker and docker compose functionality, needed by existing CI tasks in our projects..

**Comment by telackey** [comment]
I have opened up a couple of PRs against gitea/act_runner and a couple more against our own repos for the functionality that we need:

act_runner:
https://gitea.com/gitea/act_runner/pulls/83 (merged)
https://gitea.com/gitea/act_runner/pulls/84 (under review)

Both are incorporated into a temporary fork we can use until they are both merged: https://github.com/telackey/act_runner

For our own repos, that led to:

https://github.com/cerc-io/hosting/pull/19
https://github.com/cerc-io/hosting/pull/23
https://github.com/cerc-io/stack-orchestrator/pull/238

So that we know have automatic deployment of act_runner via stack-orchestrator.

As regards repos, we have:

https://github.com/cerc-io/go-ethereum/pull/342
https://github.com/cerc-io/laconic-sdk/pull/38

Which are draft PRs for the minor refactoring work to deal with limitations of the Gitea actions are they stand now (see https://github.com/cerc-io/hosting/issues/25 and https://github.com/cerc-io/hosting/issues/26)

**Comment by telackey** [comment]
I think we can call this issue closed, since we've got the necessary changes made for our use, but it is worth adding an update when our changes are merged upstream.
